# Instruction made from https://geshan.com.np/blog/2022/01/redis-docker/
version: '2'

services:
  cache:
    image: redis:7.0.10-alpine
    container_name: rate-limiter-redis-cache
    restart: always
    ports:
      - '6379:6379' 
  api:
    build: .
    container_name: rate-limiter-api
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - './main:/app/main'
    depends_on:
      - cache

